/* Color design token assignation for light and dark modes */

import colors from "./colors";

const semanticColors = {
  colors: {
    light: {
      'background-caution': colors.orange[500],
      'background-caution-faded': colors.orange[50],
      'background-critical': colors.red[500],
      'background-critical-active': colors.red[700],
      'background-critical-faded': colors.red[50],
      'background-critical-hover': colors.red[600],
      'background-elevation-raised': colors.white,
      'background-info': colors.blue[500],
      'background-info-faded': colors.blue[50],
      'background-neutral': colors.white,
      'background-neutral-active': colors.gray[200],
      'background-neutral-faded': colors.gray[50],
      'background-neutral-hover': colors.gray[100],
      'background-page': colors.gray[50],
      'background-positive': colors.green[500],
      'background-positive-active': colors.green[600],
      'background-positive-faded': colors.green[50],
      'background-positive-hover': colors.green[600],
      'background-primary': colors.primary[500],
      'background-primary-active': colors.primary[700],
      'background-primary-faded': colors.primary[50],
      'background-primary-hover': colors.primary[600],
      'border-caution': colors.orange[500],
      'border-caution-faded': colors.orange[200],
      'border-critical': colors.red[500],
      'border-critical-faded': colors.red[200],
      'border-info': colors.blue[500],
      'border-info-faded': colors.blue[200],
      'border-neutral': colors.gray[500],
      'border-neutral-faded': colors.gray[200],
      'border-positive': colors.green[500],
      'border-positive-faded': colors.green[200],
      'border-primary': colors.primary[500],
      'border-primary-faded': colors.primary[200],
      'foreground-caution': colors.orange[600],
      'foreground-critical': colors.red[600],
      'foreground-info': colors.blue[600],
      'foreground-neutral': colors.gray[900],
      'foreground-neutral-faded': colors.gray[500],
      'foreground-positive': colors.green[600],
      'foreground-primary': colors.primary[600],
      'on-background-caution': colors.black,
      'on-background-critical': colors.white,
      'on-background-info': colors.white,
      'on-background-positive': colors.white,
      'on-background-primary': colors.white,
      'persistent-black': colors.black,
      'persistent-white': colors.white,
    },
    dark: { 
      'background-caution': colors.orange[400],
      'background-caution-faded': colors.orange[900],
      'background-critical': colors.red[400],
      'background-critical-active': colors.red[600],
      'background-critical-faded': colors.red[900],
      'background-critical-hover': colors.red[500],
      'background-elevation-raised': colors.gray[800],
      'background-info': colors.blue[400],
      'background-info-faded': colors.blue[900],
      'background-neutral': colors.gray[800],
      'background-neutral-active': colors.gray[600],
      'background-neutral-faded': colors.gray[700],
      'background-neutral-hover': colors.gray[700],
      'background-page': colors.gray[900],
      'background-positive': colors.green[400],
      'background-positive-active': colors.green[600],
      'background-positive-faded': colors.green[900],
      'background-positive-hover': colors.green[500],
      'background-primary': colors.primary[400],
      'background-primary-active': colors.primary[600],
      'background-primary-faded': colors.primary[900],
      'background-primary-hover': colors.primary[500],
      'border-caution': colors.orange[500],
      'border-caution-faded': colors.orange[800],
      'border-critical': colors.red[500],
      'border-critical-faded': colors.red[800],
      'border-info': colors.blue[500],
      'border-info-faded': colors.blue[800],
      'border-neutral': colors.gray[600],
      'border-neutral-faded': colors.gray[700],
      'border-positive': colors.green[500],
      'border-positive-faded': colors.green[800],
      'border-primary': colors.primary[500],
      'border-primary-faded': colors.primary[800],
      'foreground-caution': colors.orange[300],
      'foreground-critical': colors.red[300],
      'foreground-info': colors.blue[300],
      'foreground-neutral': colors.white,
      'foreground-neutral-faded': colors.gray[400],
      'foreground-positive': colors.green[300],
      'foreground-primary': colors.primary[300],
      'on-background-caution': colors.gray[900],
      'on-background-critical': colors.gray[900],
      'on-background-info': colors.gray[900],
      'on-background-positive': colors.gray[900],
      'on-background-primary': colors.gray[900],
      'persistent-black': colors.black,
      'persistent-white': colors.white,
    },
  }
}

export default semanticColors;